# Generated by Django 2.2.4 on 2022-06-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_show_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='release_date',
        ),
    ]
